#!/bin/sh

case "$1" in
start)
echo "Starting gpio-watch"
start-stop-daemon --start --quiet -b -m -p/var/run/gpio-watch.pid --exec /usr/local/bin/gpio-watch -- -s /usr/local/etc/gpio-scripts -e switch 17 21 22
;;
stop)
echo "Stopping gpio-watch"
start-stop-daemon --stop --quiet --pidfile /var/run/qpio-watch.pid
sudo rm -f /var/run/qpio-watch.pid
;;
	
*)
echo "Usage: /usr/local/etc/init.d/gpio-watch {start|stop}"
exit 1
;;
esac
exit 0
